### ISSUE TITLE
Open local documentation ?

### ISSUE THREAD

**Issue by kl0tl** [talitore/Unity3DReference#1]
Hi,

Wouldn’t it be better to open the local documentation bundled with Unity ? It would be a bit faster and would allow to work offline.

**Comment by talitore** [comment]
Hey there @Kl0tl!

Sorry I didn't see this sooner. For some reason I had Unwatched this repo and didn't get notifications. I'll look into these issues and your PR's ASAP!

**Comment by talitore** [comment]
Closed by #3
