### ISSUE TITLE
 sublime text 3 Reference

### ISSUE THREAD

**Issue by ghost** [talitore/Unity3DReference#2]
When press ctrl + ' no open in sublime text 3.

**Comment by talitore** [comment]
Hey there @eldervaz!

What platform are you using and can you paste the information from your console `View > Show Console`?

**Comment by rhoeberg** [comment]
This doesn't work for me either. I'm on osx. Do you need any other information?

**Comment by talitore** [comment]
@Rhoeberg Could you copy/paste the info from your console before & after trying? Also I want to clarify that it's `'` the single quote and not ``` the back tick.

**Comment by rhoeberg** [comment]
Nothing appears in console after trying. When i press " ctrl + ' " it encapsulates the selected text in ' ', so maybe the other keycommand is overlapping? I also tried with "command + ' " without any result.

**Comment by talitore** [comment]
Thanks for the prompt feedback. I'll have to test this again on OSX and see if I can replicate.

Do you have any other packages installed? If so could you both list them (so I can find incompatibilities) and test this after removing them?

If not I understand; I'm about to push out an update that will allow custom hotkeys soon anyways. 

Thanks!

**Comment by rhoeberg** [comment]
I have the following package installed:
Colorsublime
Flatron (theme)
FTPSync
Material theme
Package control
Predawn (theme)
RegReplace
Cobalt2 (theme)
Unity3D

I tried uninstalling them all, still without any success.
Sounds great with a feature for custom hotkeys.

**Comment by talitore** [comment]
@Rhoeberg Sorry I've been away. I've merged #3 and this should fix this issue. I'll close this issue when it's live. Thanks again.

**Comment by talitore** [comment]
Have pushed tag `1.1.0`. Let me know how it works for you!

**Comment by rhoeberg** [comment]
@talitore Ok first I had the same problem. But after changing the keybinding works like a charm. I think it was the same problem last time. I guess the default keybinding doesn't work with mac. 
I used this instead:
{ "keys": ["super+'"], "command": "search_script_reference" }

**Comment by talitore** [comment]
It's weird that you're seeing that behavior as I use `ctrl + '` on mac myself. Oh well, glad to hear it's working!
