### ISSUE TITLE
Opens console on PC

### ISSUE THREAD

**Issue by zandergrin** [talitore/Unity3DReference#7]
CTRL + ' is the shortcut for the console on PC. Am I being dumb!?

**Comment by zandergrin** [comment]
I found the shortcut to be the button to the right of the single quote mark, and found ow to reset it. I think my default key binding file was empty for some reason.

**Comment by talitore** [comment]
@zandergrin sorry to hear that. I'ma gonna close this issue as it seems resolved. Thanks for using the plugin!
